[project]
name = "repl-nix-deeridentifierai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "keras==2.11.0",
    "numpy>=2.1.3",
    "openai>=1.57.0",
    "opencv-python>=4.10.0.84",
    "streamlit>=1.40.2",
]
